services:
  - type: web
    name: ecommerce-backend
    env: python
    plan: free
    buildCommand: |
      sudo apt-get update
      sudo apt-get install -y python3.12 python3.12-venv
      python3.12 -m venv .venv
      . .venv/bin/activate
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: .venv/bin/gunicorn app:app
    region: oregon
    pythonVersion: 3.12.6
